#!/usr/bin/env bash
# Produce a .dev.vars holding ANTHROPIC_API_KEY for `wrangler dev`.
#
# Order of preference:
#   1. A .dev.vars you wrote yourself — left completely alone.
#   2. Doppler, if this repo is set up against a project that has the key.
#
# Writing an empty key is never acceptable: the Worker would boot fine and then
# fail only when you actually tried to parse an entry, which reads like a broken
# app rather than missing configuration.
set -euo pipefail

MARKER="# generated by scripts/dev-vars.sh — safe to delete"

if [ -f .dev.vars ] && grep -q '^ANTHROPIC_API_KEY=.\+' .dev.vars; then
  if ! grep -qF "$MARKER" .dev.vars; then
    echo "dev-vars: using your existing .dev.vars (not overwriting)"
    exit 0
  fi
fi

if key=$(doppler secrets get ANTHROPIC_API_KEY --plain 2>/dev/null) && [ -n "$key" ]; then
  printf '%s\nANTHROPIC_API_KEY=%s\n' "$MARKER" "$key" > .dev.vars
  echo "dev-vars: wrote .dev.vars from Doppler"
  exit 0
fi

cat >&2 <<'EOF'
dev-vars: could not resolve ANTHROPIC_API_KEY.

Doppler has no ANTHROPIC_API_KEY reachable from this repo. Either:

  1. Write the key once, by hand (gitignored, simplest):
       echo 'ANTHROPIC_API_KEY=sk-ant-...' > .dev.vars

  2. Or put it in Doppler and point this repo at that project:
       doppler setup --project <project> --config dev
       doppler secrets set ANTHROPIC_API_KEY

Everything except the natural-language parse box works without a key —
`npm run dev` alone is enough to see and click through the whole UI.
EOF
exit 1
