// The canonical ingredient dictionary. This is the load-bearing table of the
// whole product: matching is only as good as the collapse from "2 boneless
// skinless chicken thighs, trimmed" to `chicken`.
//
// Each entry: id (also the display name unless `label`), a category that
// drives diet inference, synonyms matched against cleaned ingredient text,
// and flags:
//   staple   default member of the Spicerack (assumed on hand)
//   gluten   contains gluten (drives the weak gluten-free inference)
//   animal   animal-derived even though the category is not obviously so
//            (fish sauce is a condiment; honey is a sweetener)
//
// Categories: meat poultry fish shellfish egg dairy legume grain pasta bread
//             vegetable fruit herb spice oil condiment sweetener nut baking
//             beverage other
//
// Grow this from real query logs and the `unresolved` admin list, not from
// the corpus — the corpus has ten thousand ways to say "salt".

const c = (id, category, synonyms = [], flags = {}) => ({
  id,
  label: flags.label || id.replace(/-/g, " "),
  category,
  synonyms: [id.replace(/-/g, " "), ...synonyms],
  staple: !!flags.staple,
  gluten: !!flags.gluten,
  animal: !!flags.animal,
});

export const CANONICALS = [
  // --- meat ------------------------------------------------------------
  c("beef", "meat", ["ground beef", "beef mince", "minced beef", "steak", "sirloin", "ribeye", "rib eye", "flank steak", "skirt steak", "chuck roast", "chuck", "brisket", "beef stew meat", "stew beef", "short ribs", "beef short rib", "roast beef", "filet mignon", "beef tenderloin", "hamburger", "beef chuck", "top round", "london broil", "tri tip", "oxtail", "beef shank", "beef ribs", "flat iron", "scotch fillet", "scotch fillet steak", "rump steak", "rump", "porterhouse", "t-bone", "t-bone steak", "eye fillet", "beef fillet", "fillet steak", "minute steak", "hanger steak", "bavette", "cube steak", "beef strips", "stir fry beef", "stir-fry beef", "beef stir fry strips", "beef cubes", "stewing beef", "braising steak", "blade steak", "beef brisket", "corned beef", "pastrami", "beef jerky", "wagyu", "beef patties", "beef burgers", "meatballs", "beef meatballs", "frozen meatballs"]),
  c("pork", "meat", ["pork chop", "pork loin", "pork tenderloin", "pork shoulder", "pork butt", "boston butt", "ground pork", "pork mince", "pork belly", "pork ribs", "spare ribs", "baby back ribs", "pulled pork", "pork roast", "pork cutlet"]),
  c("bacon", "meat", ["bacon strips", "streaky bacon", "bacon bits", "pancetta", "back bacon", "turkey bacon", "bacon lardons", "lardons"]),
  c("ham", "meat", ["prosciutto", "deli ham", "smoked ham", "ham hock", "serrano ham", "ham steak", "black forest ham"]),
  c("sausage", "meat", ["italian sausage", "sausages", "breakfast sausage", "chorizo", "kielbasa", "bratwurst", "andouille", "sausage meat", "hot dog", "hot dogs", "frankfurter", "pepperoni", "salami", "merguez"]),
  c("lamb", "meat", ["ground lamb", "lamb chop", "lamb shoulder", "leg of lamb", "lamb shank", "lamb mince", "lamb leg"]),
  c("veal", "meat", ["veal cutlet", "veal shank", "ground veal"]),
  c("venison", "meat", ["deer meat", "elk", "bison", "ground bison"]),
  // --- poultry ---------------------------------------------------------
  c("chicken", "poultry", ["chicken fillet", "chicken fillets", "chicken breast fillets", "chicken thigh fillets", "chicken breast", "chicken breasts", "chicken thigh", "chicken thighs", "chicken drumstick", "chicken drumsticks", "chicken leg", "chicken legs", "chicken wing", "chicken wings", "whole chicken", "rotisserie chicken", "chicken tenders", "chicken tenderloin", "chicken cutlet", "chicken cutlets", "ground chicken", "chicken mince", "shredded chicken", "cooked chicken", "leftover chicken", "chicken pieces", "chicken quarters", "boneless skinless chicken", "chicken meat"]),
  c("turkey", "poultry", ["ground turkey", "turkey breast", "turkey mince", "deli turkey", "turkey thigh", "leftover turkey", "turkey cutlet", "smoked turkey", "turkey sausage"]),
  c("duck", "poultry", ["duck breast", "duck leg", "duck confit"]),
  // --- fish ------------------------------------------------------------
  c("salmon", "fish", ["salmon fillet", "salmon fillets", "salmon portions", "skinless salmon", "skin-on salmon", "smoked salmon", "canned salmon", "lox", "salmon steak"]),
  c("tuna", "fish", ["canned tuna", "tuna steak", "tinned tuna", "ahi tuna", "albacore", "tuna in oil", "tuna in water"]),
  c("cod", "fish", ["cod fillet", "cod fillets", "cod loin", "haddock", "pollock", "hake"]),
  c("white-fish", "fish", ["white fish", "whitefish", "tilapia", "halibut", "sea bass", "snapper", "red snapper", "flounder", "sole", "mahi mahi", "mahi-mahi", "grouper", "catfish", "barramundi", "fish fillet", "fish fillets", "firm white fish", "swordfish", "monkfish", "bass", "perch", "walleye", "trout", "rainbow trout", "arctic char", "branzino"]),
  c("anchovy", "fish", ["anchovies", "anchovy fillet", "anchovy fillets", "anchovy paste"]),
  c("sardine", "fish", ["sardines", "canned sardines", "mackerel", "canned mackerel"]),
  // --- shellfish -------------------------------------------------------
  c("shrimp", "shellfish", ["prawns", "prawn", "jumbo shrimp", "large shrimp", "raw shrimp", "cooked shrimp", "frozen shrimp", "tiger prawns", "king prawns"]),
  c("crab", "shellfish", ["crab meat", "crabmeat", "lump crab", "crab legs", "imitation crab", "surimi"]),
  c("scallop", "shellfish", ["scallops", "sea scallops", "bay scallops"]),
  c("mussel", "shellfish", ["mussels", "clams", "clam", "littleneck clams", "canned clams", "clam juice", "oysters", "oyster"]),
  c("squid", "shellfish", ["calamari", "octopus", "cuttlefish"]),
  c("lobster", "shellfish", ["lobster tail", "lobster tails", "lobster meat", "crawfish", "crayfish", "langoustine"]),
  // --- egg & dairy -----------------------------------------------------
  c("egg", "egg", ["eggs", "large egg", "large eggs", "egg yolk", "egg yolks", "egg white", "egg whites", "whole egg", "whole eggs", "hard boiled egg", "hard-boiled eggs", "beaten egg", "medium eggs", "extra large eggs"]),
  c("milk", "dairy", ["whole milk", "skim milk", "2% milk", "low-fat milk", "lowfat milk", "dairy milk", "cow's milk", "cows milk", "evaporated milk", "buttermilk", "milk of choice", "milk of your choice"]),
  c("cream", "dairy", ["heavy cream", "heavy whipping cream", "whipping cream", "double cream", "single cream", "light cream", "half and half", "half-and-half", "creme fraiche", "crème fraîche", "thickened cream", "pouring cream"]),
  c("sour-cream", "dairy", ["sour cream", "soured cream", "mexican crema", "crema"]),
  c("yogurt", "dairy", ["greek yogurt", "plain yogurt", "yoghurt", "greek yoghurt", "natural yoghurt", "natural yogurt", "whole milk yogurt", "skyr", "plain greek yogurt", "labneh"]),
  c("butter", "dairy", ["unsalted butter", "salted butter", "melted butter", "softened butter", "ghee", "clarified butter", "butter or margarine", "cold butter"], { staple: true }),
  c("parmesan", "dairy", ["parmesan cheese", "parmigiano reggiano", "parmigiano-reggiano", "grated parmesan", "parmigiano", "parmesan or pecorino"], { staple: true }),
  c("ice-cream", "dairy", ["ice cream", "vanilla ice cream", "gelato"]),
  c("condensed-milk", "dairy", ["sweetened condensed milk", "condensed milk", "dulce de leche"]),
  // --- legumes & soy ---------------------------------------------------
  c("tofu", "legume", ["firm tofu", "extra firm tofu", "extra-firm tofu", "silken tofu", "soft tofu", "bean curd", "tempeh", "seitan"]),
  c("chickpea", "legume", ["chickpeas", "garbanzo beans", "garbanzo", "garbanzos", "canned chickpeas", "chana", "chickpea flour", "gram flour", "besan"]),
  c("black-bean", "legume", ["black beans", "canned black beans", "turtle beans"]),
  c("kidney-bean", "legume", ["kidney beans", "red kidney beans", "red beans"]),
  c("white-bean", "legume", ["white beans", "cannellini", "cannellini beans", "great northern beans", "navy beans", "butter beans", "lima beans", "haricot beans", "borlotti", "cranberry beans"]),
  c("pinto-bean", "legume", ["pinto beans", "refried beans"]),
  c("lentil", "legume", ["lentils", "red lentils", "green lentils", "brown lentils", "french lentils", "puy lentils", "black lentils", "beluga lentils", "split red lentils", "dal", "dahl", "moong dal", "toor dal", "urad dal", "chana dal"]),
  c("edamame", "legume", ["soybeans", "soy beans", "shelled edamame"]),
  c("peanut", "nut", ["peanuts", "roasted peanuts", "salted peanuts", "crushed peanuts"]),
  c("peanut-butter", "nut", ["peanut butter", "creamy peanut butter", "crunchy peanut butter", "natural peanut butter"], { staple: true }),
  c("split-pea", "legume", ["split peas", "green split peas", "yellow split peas"]),
  c("green-bean", "vegetable", ["green beans", "string beans", "haricots verts", "haricot vert", "french beans", "runner beans"]),
  // --- grains, pasta, bread --------------------------------------------
  c("rice", "grain", ["white rice", "long grain rice", "long-grain rice", "jasmine rice", "basmati rice", "basmati", "brown rice", "cooked rice", "leftover rice", "short grain rice", "sushi rice", "arborio rice", "arborio", "risotto rice", "wild rice", "day old rice", "day-old rice", "medium grain rice", "uncooked rice", "rice of choice", "calrose rice", "sticky rice", "glutinous rice", "black rice", "red rice", "carnaroli", "bomba rice", "minute rice", "instant rice"]),
  c("quinoa", "grain", ["cooked quinoa", "tricolor quinoa", "red quinoa", "white quinoa"]),
  c("oats", "grain", ["rolled oats", "old fashioned oats", "old-fashioned oats", "quick oats", "steel cut oats", "steel-cut oats", "oatmeal", "porridge oats", "instant oats"]),
  c("couscous", "grain", ["israeli couscous", "pearl couscous", "moroccan couscous"], { gluten: true }),
  c("bulgur", "grain", ["bulgur wheat", "cracked wheat", "farro", "freekeh", "barley", "pearl barley", "pearled barley", "wheat berries", "spelt"], { gluten: true }),
  c("cornmeal", "grain", ["polenta", "grits", "corn meal", "masa harina", "masa", "corn flour", "fine cornmeal", "coarse cornmeal", "semolina"]),
  c("pasta", "pasta", ["spaghetti", "penne", "rigatoni", "fusilli", "fettuccine", "linguine", "linguini", "farfalle", "bow tie pasta", "bowtie pasta", "macaroni", "elbow macaroni", "orzo", "lasagna noodles", "lasagne sheets", "ziti", "rotini", "shells", "pasta shells", "orecchiette", "tagliatelle", "pappardelle", "bucatini", "angel hair", "cavatappi", "gemelli", "ditalini", "dried pasta", "short pasta", "pasta of choice", "any pasta", "gnocchi", "tortellini", "ravioli", "spaghettini", "capellini", "conchiglie", "pasta shape", "campanelle", "mafalda", "lasagna sheets", "lasagne", "vermicelli"], { gluten: true }),
  c("noodles", "pasta", ["egg noodles", "ramen noodles", "ramen", "instant noodles", "udon", "udon noodles", "soba", "soba noodles", "rice noodles", "rice vermicelli", "glass noodles", "cellophane noodles", "lo mein noodles", "chow mein noodles", "wide rice noodles", "pad thai noodles", "wheat noodles", "asian noodles", "somen", "flat rice noodles", "hokkien noodles", "shirataki", "dan dan noodles", "wonton noodles", "yakisoba"], { gluten: true }),
  c("bread", "bread", ["sandwich bread", "white bread", "sourdough", "sourdough bread", "baguette", "french bread", "crusty bread", "day old bread", "day-old bread", "stale bread", "whole wheat bread", "brioche", "ciabatta", "rolls", "dinner rolls", "burger buns", "hamburger buns", "hot dog buns", "buns", "slices of bread", "bread slices", "sliced bread", "italian bread", "rye bread", "challah", "focaccia", "naan", "flatbread", "flatbreads", "pita", "pita bread", "pitas", "bread of choice", "bread roll", "english muffin", "english muffins", "bagel", "bagels", "croissant", "croissants", "texas toast", "garlic bread", "toast", "crostini"], { gluten: true }),
  c("breadcrumbs", "bread", ["bread crumbs", "panko", "panko breadcrumbs", "panko bread crumbs", "italian breadcrumbs", "seasoned breadcrumbs", "fresh breadcrumbs", "dried breadcrumbs", "croutons", "crackers", "cracker crumbs", "ritz crackers", "saltines", "saltine crackers"], { gluten: true, staple: true }),
  c("tortilla", "bread", ["tortillas", "flour tortillas", "corn tortillas", "flour tortilla", "corn tortilla", "wraps", "tortilla wraps", "taco shells", "tostadas", "tortilla chips", "chips"]),
  c("flour", "baking", ["all purpose flour", "all-purpose flour", "plain flour", "ap flour", "bread flour", "self rising flour", "self-rising flour", "self-raising flour", "whole wheat flour", "wholemeal flour", "cake flour", "pastry flour", "00 flour", "white flour", "wheat flour", "flour for dusting"], { gluten: true, staple: true }),
  c("cornstarch", "baking", ["corn starch", "cornflour", "arrowroot", "arrowroot powder", "arrowroot starch", "potato starch", "tapioca starch", "tapioca flour"], { staple: true }),
  c("almond-flour", "baking", ["almond flour", "almond meal", "ground almonds", "coconut flour", "rice flour", "gluten free flour", "gluten-free flour", "gluten free flour blend", "1:1 gluten free flour", "oat flour", "buckwheat flour", "chestnut flour", "cassava flour"]),
  c("pizza-dough", "bread", ["pizza dough", "pizza crust", "puff pastry", "phyllo", "filo", "phyllo dough", "filo pastry", "pie crust", "pie dough", "shortcrust pastry", "crescent rolls", "crescent dough", "biscuit dough", "wonton wrappers", "dumpling wrappers", "egg roll wrappers", "spring roll wrappers", "rice paper", "gyoza wrappers"], { gluten: true }),
  c("yeast", "baking", ["active dry yeast", "instant yeast", "dry yeast", "rapid rise yeast", "fresh yeast", "bread machine yeast"], { staple: true }),
  c("baking-powder", "baking", ["baking powder"], { staple: true }),
  c("baking-soda", "baking", ["baking soda", "bicarbonate of soda", "bicarb", "bicarb soda", "sodium bicarbonate"], { staple: true }),
  c("cocoa", "baking", ["cocoa powder", "unsweetened cocoa powder", "unsweetened cocoa", "dutch process cocoa", "dutch-process cocoa", "cacao powder", "cacao"], { staple: true }),
  c("chocolate", "baking", ["chocolate chips", "semisweet chocolate", "semi-sweet chocolate", "dark chocolate", "milk chocolate", "bittersweet chocolate", "white chocolate", "chocolate chunks", "semi sweet chocolate chips", "baking chocolate", "unsweetened chocolate", "chocolate bar", "dark chocolate chips", "white chocolate chips", "milk chocolate chips", "nutella", "chocolate hazelnut spread"]),
  c("vanilla", "baking", ["vanilla extract", "pure vanilla extract", "vanilla bean", "vanilla bean paste", "vanilla essence", "vanilla paste"], { staple: true }),
  c("gelatin", "baking", ["gelatine", "unflavored gelatin", "gelatin powder", "gelatin sheets"], { animal: true }),
  // --- vegetables ------------------------------------------------------
  c("onion", "vegetable", ["yellow onion", "white onion", "red onion", "onions", "yellow onions", "red onions", "sweet onion", "vidalia onion", "brown onion", "large onion", "small onion", "medium onion", "diced onion", "chopped onion", "onion of choice", "spanish onion", "pearl onions", "cipollini"], { staple: true }),
  c("shallot", "vegetable", ["shallots", "french shallot", "eschalot", "banana shallot"]),
  c("green-onion", "vegetable", ["green onions", "scallions", "scallion", "spring onions", "spring onion", "salad onions", "green onion tops"]),
  c("leek", "vegetable", ["leeks"]),
  c("garlic", "vegetable", ["garlic cloves", "cloves garlic", "cloves of garlic", "garlic clove", "minced garlic", "fresh garlic", "garlic paste", "crushed garlic", "head of garlic", "garlic bulb", "roasted garlic", "black garlic", "garlic, minced"], { staple: true }),
  c("ginger", "vegetable", ["fresh ginger", "ginger root", "grated ginger", "minced ginger", "ginger paste", "ginger, grated", "fresh ginger root", "piece of ginger", "gingerroot"], { staple: true }),
  c("tomato", "vegetable", ["tomatoes", "roma tomatoes", "roma tomato", "plum tomatoes", "cherry tomatoes", "grape tomatoes", "fresh tomatoes", "ripe tomatoes", "beefsteak tomato", "heirloom tomatoes", "vine tomatoes", "large tomato", "medium tomatoes", "tomatoes on the vine", "campari tomatoes", "green tomatoes"]),
  c("canned-tomato", "vegetable", ["canned tomatoes", "crushed tomatoes", "diced tomatoes", "canned diced tomatoes", "whole peeled tomatoes", "san marzano tomatoes", "san marzano", "tomato puree", "tomato purée", "passata", "tomato sauce", "canned tomato sauce", "fire roasted tomatoes", "fire-roasted tomatoes", "chopped tomatoes", "tinned tomatoes", "tin of tomatoes", "can of tomatoes", "stewed tomatoes", "canned crushed tomatoes", "tomato passata", "rotel", "ro-tel", "tomatoes with green chiles", "marinara", "marinara sauce", "pasta sauce", "pizza sauce", "strained tomatoes", "canned whole tomatoes"], { staple: true }),
  c("tomato-paste", "condiment", ["tomato paste", "tomato concentrate", "double concentrated tomato paste"], { staple: true }),
  c("sun-dried-tomato", "vegetable", ["sun dried tomatoes", "sun-dried tomatoes", "sundried tomatoes", "sun-dried tomato", "oil-packed sun-dried tomatoes"], { staple: true }),
  c("potato", "vegetable", ["potatoes", "russet potatoes", "russet potato", "yukon gold potatoes", "yukon gold", "yukon golds", "red potatoes", "baby potatoes", "new potatoes", "fingerling potatoes", "gold potatoes", "white potatoes", "waxy potatoes", "floury potatoes", "baking potatoes", "large potatoes", "medium potatoes", "small potatoes", "idaho potatoes", "potatoes of choice", "mashed potatoes", "leftover mashed potatoes", "hash browns", "frozen hash browns", "tater tots", "french fries", "frozen fries", "potato gnocchi"]),
  c("sweet-potato", "vegetable", ["sweet potatoes", "yam", "yams", "japanese sweet potato", "garnet yam", "kumara"]),
  c("carrot", "vegetable", ["carrots", "baby carrots", "shredded carrots", "large carrot", "medium carrots", "grated carrot", "rainbow carrots"]),
  c("celery", "vegetable", ["celery stalks", "celery stalk", "celery ribs", "celery rib", "stalks celery", "celeriac", "celery root"]),
  c("bell-pepper", "vegetable", ["bell pepper", "bell peppers", "red bell pepper", "green bell pepper", "yellow bell pepper", "orange bell pepper", "red pepper", "green pepper", "yellow pepper", "capsicum", "red capsicum", "sweet pepper", "sweet peppers", "mini peppers", "roasted red peppers", "roasted red pepper", "jarred roasted peppers", "roasted peppers", "piquillo peppers", "bell peppers, any color", "peppers"]),
  c("chili-pepper", "vegetable", ["chili", "chile", "chiles", "chilies", "chillies", "chilli", "chillis", "jalapeño", "jalapeno", "jalapeños", "jalapenos", "serrano", "serrano pepper", "serrano chile", "thai chili", "thai chilies", "thai chiles", "bird's eye chili", "birds eye chili", "bird eye chili", "red chili", "green chili", "green chile", "green chiles", "habanero", "poblano", "poblano pepper", "poblanos", "anaheim pepper", "anaheim chile", "fresno chile", "fresno pepper", "scotch bonnet", "hot pepper", "hot peppers", "chipotle peppers in adobo", "chipotles in adobo", "chipotle in adobo", "chipotle pepper", "chipotle chiles", "canned green chiles", "diced green chiles", "hatch chiles", "dried chiles", "dried chilies", "guajillo", "guajillo chiles", "ancho chiles", "ancho chile", "arbol chiles", "chile de arbol", "pasilla", "cayenne pepper, fresh", "long red chili", "red chile", "chile pepper", "chili pepper", "chili peppers", "chile peppers", "shishito peppers", "padron peppers", "pepperoncini", "banana peppers", "cherry peppers", "calabrian chiles", "calabrian chili"]),
  c("cucumber", "vegetable", ["cucumbers", "english cucumber", "persian cucumbers", "persian cucumber", "mini cucumbers", "lebanese cucumber", "kirby cucumbers"]),
  c("zucchini", "vegetable", ["zucchinis", "courgette", "courgettes", "summer squash", "yellow squash", "zucchini noodles", "zoodles", "pattypan"]),
  c("eggplant", "vegetable", ["eggplants", "aubergine", "aubergines", "japanese eggplant", "chinese eggplant", "italian eggplant", "globe eggplant"]),
  c("mushroom", "vegetable", ["mushrooms", "cremini mushrooms", "cremini", "crimini mushrooms", "button mushrooms", "white mushrooms", "baby bella mushrooms", "baby bella", "baby bellas", "portobello", "portobello mushrooms", "portabella", "shiitake", "shiitake mushrooms", "oyster mushrooms", "king oyster mushrooms", "wild mushrooms", "mixed mushrooms", "porcini", "dried porcini", "dried mushrooms", "chanterelles", "enoki", "maitake", "sliced mushrooms", "chestnut mushrooms", "mushrooms of choice"]),
  c("spinach", "vegetable", ["baby spinach", "fresh spinach", "frozen spinach", "spinach leaves", "chopped spinach", "frozen chopped spinach"]),
  c("kale", "vegetable", ["lacinato kale", "tuscan kale", "curly kale", "dinosaur kale", "baby kale", "cavolo nero", "kale leaves"]),
  c("lettuce", "vegetable", ["romaine", "romaine lettuce", "iceberg lettuce", "iceberg", "butter lettuce", "bibb lettuce", "boston lettuce", "little gem", "gem lettuce", "mixed greens", "salad greens", "spring mix", "mesclun", "lettuce leaves", "leaf lettuce", "green leaf lettuce", "red leaf lettuce", "salad leaves", "baby greens", "arugula", "rocket", "baby arugula", "watercress", "endive", "radicchio", "frisee", "frisée", "escarole"]),
  c("cabbage", "vegetable", ["green cabbage", "red cabbage", "napa cabbage", "savoy cabbage", "chinese cabbage", "shredded cabbage", "coleslaw mix", "slaw mix", "purple cabbage", "white cabbage", "head of cabbage", "bok choy", "baby bok choy", "pak choi", "choy sum", "gai lan", "chinese broccoli", "brussels sprouts", "brussel sprouts", "sauerkraut", "kimchi"]),
  c("broccoli", "vegetable", ["broccoli florets", "broccolini", "frozen broccoli", "head of broccoli", "broccoli crowns", "broccoli rabe", "rapini", "romanesco", "broccoli stems"]),
  c("cauliflower", "vegetable", ["cauliflower florets", "head of cauliflower", "cauliflower rice", "riced cauliflower", "frozen cauliflower"]),
  c("corn", "vegetable", ["sweet corn", "corn kernels", "frozen corn", "canned corn", "corn on the cob", "ears of corn", "ear of corn", "fresh corn", "creamed corn", "baby corn", "sweetcorn", "corn cobs", "grilled corn"]),
  c("peas", "vegetable", ["frozen peas", "green peas", "garden peas", "sugar snap peas", "snap peas", "snow peas", "mangetout", "petite peas", "english peas", "pea shoots", "sweet peas"]),
  c("asparagus", "vegetable", ["asparagus spears", "asparagus stalks", "thin asparagus"]),
  c("squash", "vegetable", ["butternut squash", "butternut", "acorn squash", "kabocha", "kabocha squash", "delicata squash", "spaghetti squash", "pumpkin", "pumpkin puree", "pumpkin purée", "canned pumpkin", "winter squash", "hubbard squash", "honeynut squash", "pumpkin flesh"]),
  c("beet", "vegetable", ["beets", "beetroot", "beetroots", "golden beets", "cooked beets", "roasted beets"]),
  c("radish", "vegetable", ["radishes", "daikon", "daikon radish", "watermelon radish", "turnip", "turnips", "rutabaga", "swede", "kohlrabi", "parsnip", "parsnips"]),
  c("avocado", "fruit", ["avocados", "ripe avocado", "ripe avocados", "hass avocado", "guacamole"]),
  c("olive", "vegetable", ["olives", "kalamata olives", "kalamata", "black olives", "green olives", "castelvetrano olives", "pitted olives", "sliced olives", "niçoise olives", "nicoise olives", "mixed olives", "manzanilla olives"], { staple: true }),
  c("artichoke", "vegetable", ["artichokes", "artichoke hearts", "canned artichoke hearts", "marinated artichoke hearts", "jarred artichokes", "frozen artichoke hearts", "hearts of palm"]),
  c("fennel", "vegetable", ["fennel bulb", "fresh fennel", "fennel bulbs", "fennel fronds"]),
  c("okra", "vegetable", ["frozen okra", "bhindi", "ladies fingers"]),
  c("seaweed", "vegetable", ["nori", "nori sheets", "kombu", "wakame", "dried seaweed", "roasted seaweed", "dulse", "kelp"]),
  c("bean-sprout", "vegetable", ["bean sprouts", "mung bean sprouts", "sprouts", "alfalfa sprouts"]),
  c("water-chestnut", "vegetable", ["water chestnuts", "bamboo shoots", "lotus root"]),
  c("plantain", "fruit", ["plantains", "green plantains", "ripe plantains", "yuca", "cassava", "taro", "jicama"]),
  c("frozen-vegetables", "vegetable", ["frozen mixed vegetables", "mixed vegetables", "frozen vegetables", "mixed veg", "frozen veg", "stir fry vegetables", "stir-fry vegetables", "frozen stir fry mix", "vegetable medley"]),
  // --- fruit -----------------------------------------------------------
  c("lemon", "fruit", ["lemons", "lemon juice", "fresh lemon juice", "lemon zest", "juice of 1 lemon", "juice of lemon", "zest of lemon", "lemon wedges", "lemon slices", "meyer lemon", "preserved lemon", "preserved lemons", "lemon, juiced", "lemon, zested", "large lemon", "juice and zest of 1 lemon"], { staple: true }),
  c("lime", "fruit", ["limes", "lime juice", "fresh lime juice", "lime zest", "juice of 1 lime", "juice of lime", "lime wedges", "lime, juiced", "key limes", "kaffir lime leaves", "makrut lime leaves", "lime leaves"]),
  c("orange", "fruit", ["oranges", "orange juice", "fresh orange juice", "orange zest", "navel orange", "blood orange", "mandarin", "mandarins", "clementine", "clementines", "tangerine", "mandarin oranges", "orange segments", "juice of 1 orange", "cara cara orange"]),
  c("apple", "fruit", ["apples", "granny smith", "granny smith apples", "honeycrisp", "honeycrisp apples", "gala apples", "fuji apples", "green apple", "red apple", "applesauce", "apple sauce", "unsweetened applesauce", "baking apples", "tart apples", "pink lady apples", "braeburn apples"]),
  c("banana", "fruit", ["bananas", "ripe banana", "ripe bananas", "overripe bananas", "very ripe bananas", "frozen banana", "frozen bananas", "mashed banana"]),
  c("berries", "fruit", ["strawberries", "strawberry", "blueberries", "blueberry", "raspberries", "raspberry", "blackberries", "blackberry", "mixed berries", "frozen berries", "fresh berries", "frozen blueberries", "frozen strawberries", "frozen raspberries", "cranberries", "fresh cranberries", "frozen mixed berries", "boysenberries", "gooseberries", "currants", "red currants", "black currants", "huckleberries"]),
  c("grape", "fruit", ["grapes", "red grapes", "green grapes", "seedless grapes", "concord grapes"]),
  c("stone-fruit", "fruit", ["peach", "peaches", "nectarine", "nectarines", "plum", "plums", "apricot", "apricots", "cherry", "cherries", "fresh cherries", "frozen cherries", "pitted cherries", "sweet cherries", "sour cherries", "pluots", "frozen peaches", "canned peaches"]),
  c("pear", "fruit", ["pears", "bosc pear", "bosc pears", "bartlett pears", "anjou pears", "asian pear", "asian pears"]),
  c("mango", "fruit", ["mangoes", "mangos", "ripe mango", "frozen mango", "mango chunks", "green mango"]),
  c("pineapple", "fruit", ["fresh pineapple", "pineapple chunks", "canned pineapple", "crushed pineapple", "pineapple juice", "pineapple rings"]),
  c("melon", "fruit", ["watermelon", "cantaloupe", "honeydew", "honeydew melon", "rockmelon", "galia melon"]),
  c("coconut", "fruit", ["shredded coconut", "coconut flakes", "desiccated coconut", "unsweetened shredded coconut", "toasted coconut", "coconut chips", "fresh coconut", "sweetened coconut", "unsweetened coconut"]),
  c("coconut-milk", "beverage", ["coconut milk", "canned coconut milk", "full fat coconut milk", "full-fat coconut milk", "light coconut milk", "coconut cream", "unsweetened coconut milk", "can coconut milk", "lite coconut milk", "coconut milk (canned)"], { staple: true }),
  c("dried-fruit", "fruit", ["raisins", "golden raisins", "sultanas", "dried cranberries", "craisins", "dates", "medjool dates", "pitted dates", "dried apricots", "dried figs", "figs", "fresh figs", "prunes", "dried cherries", "dried mango", "dried blueberries", "dried currants", "zante currants", "date paste", "date syrup"]),
  c("pomegranate", "fruit", ["pomegranate seeds", "pomegranate arils", "pomegranate molasses", "pomegranate juice"]),
  c("kiwi", "fruit", ["kiwis", "kiwi fruit", "kiwifruit", "passion fruit", "passionfruit", "dragon fruit", "papaya", "guava", "lychee", "persimmon", "persimmons", "starfruit"]),
  c("grapefruit", "fruit", ["grapefruits", "pink grapefruit", "ruby red grapefruit", "grapefruit juice", "pomelo", "yuzu", "yuzu juice"]),
  c("rhubarb", "fruit", ["fresh rhubarb", "frozen rhubarb", "rhubarb stalks"]),
  c("tomatillo", "vegetable", ["tomatillos", "salsa verde", "green salsa"]),
  // --- herbs -----------------------------------------------------------
  c("parsley", "herb", ["fresh parsley", "flat leaf parsley", "flat-leaf parsley", "italian parsley", "curly parsley", "parsley leaves", "chopped parsley", "dried parsley", "parsley, chopped"]),
  c("cilantro", "herb", ["fresh cilantro", "coriander leaves", "fresh coriander", "coriander leaf", "cilantro leaves", "chopped cilantro", "cilantro, chopped", "coriander, chopped", "coriander (cilantro)", "cilantro (coriander)", "bunch cilantro", "bunch coriander", "coriander stems", "cilantro stems", "fresh coriander leaves"]),
  c("basil", "herb", ["fresh basil", "basil leaves", "thai basil", "fresh basil leaves", "chopped basil", "torn basil", "basil, torn", "sweet basil", "holy basil", "bunch basil"]),
  c("dried-basil", "spice", ["dried basil"], { staple: true }),
  c("mint", "herb", ["fresh mint", "mint leaves", "spearmint", "peppermint", "fresh mint leaves", "chopped mint", "dried mint"]),
  c("dill", "herb", ["fresh dill", "dill weed", "chopped dill", "dried dill", "dill fronds", "dill sprigs"]),
  c("rosemary", "herb", ["fresh rosemary", "rosemary sprigs", "rosemary sprig", "dried rosemary", "chopped rosemary", "sprig rosemary", "sprigs rosemary", "rosemary leaves"], { staple: true }),
  c("thyme", "herb", ["fresh thyme", "thyme sprigs", "thyme sprig", "dried thyme", "thyme leaves", "sprigs thyme", "sprig thyme", "lemon thyme", "fresh thyme leaves"], { staple: true }),
  c("oregano", "spice", ["dried oregano", "fresh oregano", "mexican oregano", "oregano leaves", "greek oregano"], { staple: true }),
  c("sage", "herb", ["fresh sage", "sage leaves", "dried sage", "ground sage", "rubbed sage"]),
  c("chives", "herb", ["fresh chives", "chopped chives", "garlic chives", "chive"]),
  c("tarragon", "herb", ["fresh tarragon", "dried tarragon", "marjoram", "dried marjoram", "fresh marjoram", "chervil", "lemongrass", "lemon grass", "lemongrass stalk", "lemongrass stalks", "curry leaves", "fresh curry leaves", "bay leaves", "bay leaf", "dried bay leaves", "fresh bay leaves", "lovage", "sorrel", "shiso", "perilla", "epazote", "savory", "lavender", "culinary lavender"]),
  c("italian-seasoning", "spice", ["italian seasoning", "italian herbs", "dried italian herbs", "herbes de provence", "herbs de provence", "mixed herbs", "dried mixed herbs", "poultry seasoning", "dried herbs"], { staple: true }),
  // --- spices ----------------------------------------------------------
  c("salt", "spice", ["kosher salt", "sea salt", "table salt", "fine salt", "flaky salt", "flaky sea salt", "fine sea salt", "salt and pepper", "salt & pepper", "salt and black pepper", "salt and freshly ground black pepper", "salt, to taste", "salt to taste", "salt & freshly ground black pepper", "pinch of salt", "coarse salt", "himalayan salt", "pink salt", "maldon salt", "coarse sea salt", "salt and freshly ground pepper", "salt and ground black pepper", "seasoning salt", "seasoned salt", "celery salt", "garlic salt", "onion salt", "salt, pepper"], { staple: true }),
  c("black-pepper", "spice", ["black pepper", "ground black pepper", "freshly ground black pepper", "freshly ground pepper", "cracked black pepper", "pepper", "ground pepper", "black peppercorns", "peppercorns", "white pepper", "ground white pepper", "pepper, to taste", "pepper to taste", "fresh ground pepper", "fresh ground black pepper", "freshly cracked black pepper", "coarsely ground black pepper", "freshly cracked pepper", "black pepper, to taste"], { staple: true }),
  c("cumin", "spice", ["ground cumin", "cumin seeds", "cumin seed", "whole cumin", "cumin powder", "toasted cumin"], { staple: true }),
  c("coriander", "spice", ["ground coriander", "coriander seeds", "coriander seed", "coriander powder", "whole coriander"], { staple: true }),
  c("paprika", "spice", ["sweet paprika", "hungarian paprika", "hot paprika", "regular paprika", "ground paprika", "spanish paprika"], { staple: true }),
  c("smoked-paprika", "spice", ["smoked paprika", "pimenton", "pimentón", "smoked spanish paprika", "smoked sweet paprika", "smoked hot paprika"], { staple: true }),
  c("chili-powder", "spice", ["chili powder", "chilli powder", "chile powder", "ancho chili powder", "ancho chile powder", "chipotle powder", "chipotle chili powder", "kashmiri chili powder", "kashmiri red chili powder", "red chili powder", "red chilli powder", "gochugaru", "korean chili flakes", "korean red pepper flakes", "korean chili powder", "aleppo pepper", "urfa biber", "guajillo powder", "new mexico chile powder", "chili seasoning"], { staple: true }),
  c("cayenne", "spice", ["cayenne pepper", "ground cayenne", "ground cayenne pepper", "cayenne powder"], { staple: true }),
  c("red-pepper-flakes", "spice", ["red pepper flakes", "crushed red pepper", "crushed red pepper flakes", "chili flakes", "chilli flakes", "red chili flakes", "red chilli flakes", "dried chili flakes", "dried chilli flakes", "pepper flakes", "hot pepper flakes", "chile flakes", "crushed chili flakes", "crushed chilies", "crushed red chili flakes"], { staple: true }),
  c("turmeric", "spice", ["ground turmeric", "turmeric powder", "fresh turmeric", "haldi"], { staple: true }),
  c("cinnamon", "spice", ["ground cinnamon", "cinnamon stick", "cinnamon sticks", "cinnamon powder", "cassia", "ceylon cinnamon"], { staple: true }),
  c("nutmeg", "spice", ["ground nutmeg", "freshly grated nutmeg", "grated nutmeg", "whole nutmeg", "mace", "ground mace"], { staple: true }),
  c("warm-spices", "spice", ["allspice", "ground allspice", "allspice berries", "cloves", "ground cloves", "whole cloves", "cardamom", "ground cardamom", "cardamom pods", "green cardamom", "green cardamom pods", "black cardamom", "cardamom seeds", "star anise", "anise", "anise seed", "aniseed", "fennel seeds", "fennel seed", "ground fennel", "caraway seeds", "caraway", "pumpkin pie spice", "apple pie spice", "mixed spice", "chinese five spice", "five spice", "five-spice powder", "five spice powder", "chinese five-spice", "ground ginger", "ginger powder", "dried ginger", "juniper berries", "sumac", "za'atar", "zaatar", "za atar", "nigella seeds", "kalonji", "black seeds", "fenugreek", "fenugreek seeds", "fenugreek leaves", "kasuri methi", "methi", "mustard seeds", "black mustard seeds", "yellow mustard seeds", "brown mustard seeds", "mustard powder", "dry mustard", "ground mustard", "mustard seed", "ajwain", "carom seeds", "asafoetida", "asafetida", "hing", "amchur", "amchoor", "dried mango powder", "saffron", "saffron threads", "pinch of saffron", "celery seed", "celery seeds", "dill seed", "dill seeds", "sichuan peppercorns", "szechuan peppercorns", "sichuan pepper", "szechuan pepper", "pink peppercorns", "long pepper", "grains of paradise", "mahlab", "annatto", "achiote", "achiote paste", "sazon", "sazón", "adobo seasoning", "jerk seasoning", "cajun seasoning", "creole seasoning", "old bay", "old bay seasoning", "blackening seasoning", "taco seasoning", "fajita seasoning", "everything bagel seasoning", "steak seasoning", "montreal steak seasoning", "lemon pepper", "lemon pepper seasoning", "shichimi togarashi", "togarashi", "furikake", "dukkah", "chaat", "panch phoron", "tajin", "tajín", "chinese 5 spice", "pickling spice", "bouquet garni", "seasoning blend", "all-purpose seasoning", "seasoning mix", "spice mix", "spice blend", "seasoning of choice", "dry rub", "bbq rub", "bbq seasoning", "barbecue seasoning", "harissa powder", "shawarma seasoning", "souvlaki seasoning", "greek seasoning", "italian spice", "pizza seasoning", "herb seasoning", "pumpkin spice"], { staple: true, label: "spices (misc)" }),
  c("garlic-powder", "spice", ["granulated garlic", "garlic granules", "dried garlic", "garlic flakes", "minced dried garlic"], { staple: true }),
  c("onion-powder", "spice", ["granulated onion", "dried onion", "dried minced onion", "onion flakes", "dried onion flakes", "minced onion, dried"], { staple: true }),
  // --- oils, vinegars, condiments --------------------------------------
  c("olive-oil", "oil", ["olive oil", "extra virgin olive oil", "extra-virgin olive oil", "evoo", "light olive oil", "good olive oil", "olive oil for drizzling", "olive oil, for drizzling", "olive oil for frying", "olive oil spray", "olive oil, divided", "extra virgin olive oil, divided", "olive oil, plus more"], { staple: true }),
  c("cooking-oil", "oil", ["vegetable oil", "canola oil", "neutral oil", "grapeseed oil", "avocado oil", "sunflower oil", "peanut oil", "corn oil", "cooking oil", "oil", "oil for frying", "frying oil", "neutral cooking oil", "high heat oil", "high-heat oil", "safflower oil", "rapeseed oil", "cooking spray", "nonstick cooking spray", "non-stick spray", "oil spray", "vegetable shortening", "shortening", "crisco", "lard", "beef tallow", "tallow", "duck fat", "bacon fat", "bacon grease", "bacon drippings", "schmaltz", "chicken fat", "rice bran oil", "light oil", "oil of choice", "neutral-flavored oil", "neutral flavored oil", "any neutral oil", "vegetable or canola oil", "canola or vegetable oil", "oil, for frying", "oil for cooking", "oil for the pan", "oil, divided", "mild olive oil", "neutral vegetable oil", "any oil"], { staple: true }),
  c("coconut-oil", "oil", ["virgin coconut oil", "refined coconut oil", "melted coconut oil", "unrefined coconut oil"], { staple: true }),
  c("sesame-oil", "oil", ["sesame oil", "toasted sesame oil", "dark sesame oil", "roasted sesame oil", "pure sesame oil"], { staple: true }),
  c("chili-oil", "oil", ["chili oil", "chilli oil", "chili crisp", "chilli crisp", "chili crunch", "chili crisp oil", "lao gan ma", "rayu", "hot chili oil", "sichuan chili oil", "szechuan chili oil"]),
  c("vinegar", "condiment", ["white vinegar", "distilled white vinegar", "distilled vinegar", "cider vinegar", "apple cider vinegar", "red wine vinegar", "white wine vinegar", "sherry vinegar", "champagne vinegar", "malt vinegar", "black vinegar", "chinkiang vinegar", "chinese black vinegar", "rice vinegar", "rice wine vinegar", "seasoned rice vinegar", "unseasoned rice vinegar", "acv", "raw apple cider vinegar", "vinegar of choice", "any vinegar", "white balsamic vinegar", "white balsamic", "coconut vinegar", "cane vinegar", "sushi vinegar"], { staple: true }),
  c("balsamic-vinegar", "condiment", ["balsamic vinegar", "balsamic", "balsamic glaze", "aged balsamic", "balsamic reduction"], { staple: true }),
  c("soy-sauce", "condiment", ["soy sauce", "low sodium soy sauce", "low-sodium soy sauce", "reduced sodium soy sauce", "light soy sauce", "dark soy sauce", "tamari", "shoyu", "coconut aminos", "liquid aminos", "soy sauce or tamari", "tamari or soy sauce", "regular soy sauce", "soy", "kecap manis", "sweet soy sauce", "gluten free soy sauce", "gluten-free soy sauce", "gf soy sauce", "soya sauce", "kikkoman", "thin soy sauce", "seasoned soy sauce", "mushroom soy sauce", "soy sauce, divided"], { staple: true, gluten: true }),
  c("miso", "condiment", ["miso paste", "white miso", "red miso", "yellow miso", "shiro miso", "aka miso", "awase miso", "sweet white miso", "light miso", "dark miso", "brown rice miso", "chickpea miso", "barley miso", "miso, white"]),
  c("mustard", "condiment", ["dijon mustard", "dijon", "whole grain mustard", "wholegrain mustard", "yellow mustard", "grainy mustard", "stone ground mustard", "english mustard", "spicy brown mustard", "honey mustard", "brown mustard", "prepared mustard", "german mustard", "mustard of choice", "dijon-style mustard", "coarse mustard", "hot mustard", "chinese hot mustard", "karashi"], { staple: true }),
  c("mayonnaise", "condiment", ["mayo", "kewpie mayo", "kewpie mayonnaise", "japanese mayo", "japanese mayonnaise", "light mayonnaise", "light mayo", "vegan mayo", "vegan mayonnaise", "aioli", "garlic aioli", "miracle whip", "salad dressing (mayo)", "olive oil mayonnaise", "avocado oil mayo", "hellmann's", "hellmanns", "duke's", "dukes mayonnaise", "real mayonnaise"], { staple: true, animal: true }),
  c("pickle", "vegetable", ["pickles", "dill pickles", "pickle juice", "pickle brine", "cornichons", "gherkins", "bread and butter pickles", "pickled jalapeños", "pickled jalapenos", "pickled red onions", "pickled onions", "pickled ginger", "gari", "pickled vegetables", "giardiniera", "pickled peppers", "pickled beets", "pickled cucumbers", "capers", "caper", "capers, drained", "caperberries", "salted capers", "nonpareil capers"], { staple: true }),
  c("broth", "condiment", ["chicken broth", "chicken stock", "vegetable broth", "vegetable stock", "beef broth", "beef stock", "low sodium chicken broth", "low-sodium chicken broth", "low sodium vegetable broth", "low-sodium vegetable broth", "stock", "chicken or vegetable broth", "chicken or vegetable stock", "vegetable or chicken broth", "vegetable or chicken stock", "bone broth", "chicken bone broth", "beef bone broth", "stock of choice", "broth of choice", "bouillon", "bouillon cube", "bouillon cubes", "stock cube", "stock cubes", "chicken bouillon", "chicken bouillon cube", "beef bouillon", "vegetable bouillon", "better than bouillon", "chicken base", "beef base", "vegetable base", "stock powder", "chicken stock powder", "vegetable stock powder", "bouillon powder", "chicken broth or stock", "fish stock", "fish broth", "seafood stock", "shrimp stock", "mushroom broth", "mushroom stock", "turkey stock", "turkey broth", "ham stock", "lamb stock", "pork stock", "pork broth", "homemade stock", "homemade broth", "broth", "water or broth", "broth or water", "stock or water", "water or stock", "chicken stock or broth", "hot broth", "warm broth", "hot stock", "warm stock", "vegetable stock cube", "chicken stock cube", "beef stock cube", "knorr", "maggi cube", "maggi", "consomme", "consommé", "beef consomme", "beef consommé", "chicken consomme", "chicken consommé", "cream of chicken soup", "cream of mushroom soup", "cream of celery soup", "condensed soup", "condensed cream of chicken soup", "condensed cream of mushroom soup", "tomato soup", "condensed tomato soup", "canned soup", "miso soup", "instant miso soup", "ramen seasoning packet", "ramen seasoning", "seasoning packet"], { staple: true, label: "broth or stock" }),
  c("tahini", "condiment", ["sesame paste", "tahini paste", "chinese sesame paste", "toasted sesame paste"], { staple: true }),
  c("sesame-seeds", "nut", ["sesame seeds", "toasted sesame seeds", "black sesame seeds", "white sesame seeds", "sesame seed", "toasted sesame", "sesame"], { staple: true }),
  // --- sweeteners ------------------------------------------------------
  c("brown-sugar", "sweetener", ["brown sugar", "light brown sugar", "dark brown sugar", "packed brown sugar", "soft brown sugar", "light-brown sugar", "dark-brown sugar", "golden brown sugar"], { staple: true }),
  c("honey", "sweetener", ["raw honey", "runny honey", "clear honey", "liquid honey", "honey or maple syrup", "maple syrup or honey", "honey (or maple syrup)", "local honey", "manuka honey", "hot honey", "honey, to taste"], { staple: true, animal: true }),
  c("maple-syrup", "sweetener", ["maple syrup", "pure maple syrup", "real maple syrup", "grade a maple syrup", "grade b maple syrup", "maple syrup or agave", "maple"], { staple: true }),
  // --- beverages & misc ------------------------------------------------
  c("wine", "beverage", ["white wine", "dry white wine", "red wine", "dry red wine", "rose wine", "rosé", "rosé wine", "sparkling wine", "champagne", "prosecco", "cava", "wine", "white wine or broth", "red wine or broth", "sauvignon blanc", "pinot grigio", "chardonnay", "pinot noir", "cabernet", "cabernet sauvignon", "merlot", "chianti", "riesling", "moscato", "burgundy"]),
  c("beer", "beverage", ["lager", "ale", "stout", "guinness", "pale ale", "ipa", "light beer", "dark beer", "mexican beer", "pilsner", "wheat beer", "hard cider", "cider (alcoholic)"]),
  c("spirits", "beverage", ["vodka", "gin", "rum", "dark rum", "white rum", "spiced rum", "light rum", "bourbon", "whiskey", "whisky", "scotch", "rye whiskey", "rye", "tequila", "mezcal", "cachaça", "cachaca", "pisco", "soju", "baijiu", "shochu", "everclear", "grain alcohol", "moonshine", "arak", "raki", "grappa", "eau de vie", "alcohol", "alcohol of choice", "spirit of choice"]),
  c("coffee", "beverage", ["brewed coffee", "strong coffee", "espresso", "espresso powder", "instant espresso", "instant espresso powder", "instant coffee", "instant coffee granules", "coffee grounds", "ground coffee", "cold brew", "cold brew coffee", "coffee beans", "espresso beans", "decaf coffee", "cooled coffee", "hot coffee", "black coffee", "shot of espresso", "shots of espresso", "double espresso", "coffee extract"]),
  c("nutritional-yeast", "condiment", ["nutritional yeast", "nooch", "nutritional yeast flakes", "yeast flakes", "marmite", "vegemite", "yeast extract"]),
  c("vital-wheat-gluten", "baking", ["vital wheat gluten", "wheat gluten"], { gluten: true }),
  c("protein-powder", "other", ["protein powder", "whey protein", "whey protein powder", "vanilla protein powder", "chocolate protein powder", "plant protein powder", "vegan protein powder", "pea protein", "pea protein powder", "collagen", "collagen powder", "collagen peptides", "unflavored protein powder", "casein", "casein protein", "protein powder of choice", "scoop protein powder", "scoop of protein powder"]),
  c("gluten-free-pasta", "pasta", ["gluten free pasta", "gluten-free pasta", "chickpea pasta", "lentil pasta", "brown rice pasta", "quinoa pasta", "banza", "red lentil pasta", "gf pasta", "corn pasta", "buckwheat pasta", "edamame pasta", "black bean pasta", "protein pasta", "high protein pasta", "legume pasta", "bean pasta", "palmini", "hearts of palm pasta", "kelp noodles", "konjac noodles", "miracle noodles"]),
  // --- split-out groups (coverage is only honest when groups are narrow) ---
  c("cheese", "dairy", ["shredded cheese", "cheddar", "cheddar cheese", "sharp cheddar", "mild cheddar", "monterey jack", "pepper jack", "colby jack", "colby", "swiss cheese", "gruyere", "gruyère", "gouda", "smoked gouda", "provolone", "fontina", "havarti", "muenster", "italian cheese blend", "cheese of choice", "american cheese", "brie", "camembert", "manchego", "emmental", "raclette", "jarlsberg", "asiago", "grated cheese", "cheese slices", "shredded cheddar", "melting cheese", "comte", "comté", "taleggio", "edam", "cheese curds", "velveeta", "processed cheese", "cheese, shredded", "any cheese"]),
  c("mozzarella", "dairy", ["mozzarella cheese", "fresh mozzarella", "shredded mozzarella", "burrata", "bocconcini", "low-moisture mozzarella", "low moisture mozzarella", "mozzarella pearls", "buffalo mozzarella", "scamorza"]),
  c("feta", "dairy", ["feta cheese", "crumbled feta", "block feta", "greek feta", "sheep's milk feta"]),
  c("goat-cheese", "dairy", ["goat cheese", "chevre", "chèvre", "goat's cheese", "goats cheese", "soft goat cheese"]),
  c("cream-cheese", "dairy", ["cream cheese", "neufchatel", "neufchâtel", "mascarpone", "softened cream cheese", "full fat cream cheese", "full-fat cream cheese", "whipped cream cheese", "boursin", "cream cheese, softened"]),
  c("ricotta", "dairy", ["ricotta cheese", "whole milk ricotta", "cottage cheese", "part skim ricotta", "part-skim ricotta", "fresh ricotta", "quark", "farmer cheese", "farmer's cheese", "fromage blanc"]),
  c("blue-cheese", "dairy", ["blue cheese", "bleu cheese", "gorgonzola", "stilton", "roquefort", "crumbled blue cheese", "danish blue", "cambozola"]),
  c("paneer", "dairy", ["halloumi", "haloumi", "halloumi cheese", "queso fresco", "cotija", "cotija cheese", "queso", "oaxaca cheese", "queso oaxaca", "queso blanco", "mexican cheese blend", "mexican blend cheese", "queso panela", "chihuahua cheese", "asadero", "grilling cheese", "bread cheese", "juustoleipa", "nabulsi", "akkawi", "kefalotyri", "saganaki cheese", "graviera"], { label: "paneer / halloumi / queso fresco" }),
  c("ketchup", "condiment", ["tomato ketchup", "catsup"], { staple: true }),
  c("bbq-sauce", "condiment", ["bbq sauce", "barbecue sauce", "bbq sauce of choice", "steak sauce", "a1 sauce", "a.1. sauce", "kansas city bbq sauce", "sweet baby ray's", "hp sauce", "brown sauce", "cocktail sauce", "chili sauce", "heinz chili sauce", "sweet and sour sauce", "sweet & sour sauce", "burger sauce", "special sauce", "fry sauce", "comeback sauce", "duck sauce"]),
  c("hot-sauce", "condiment", ["hot sauce", "tabasco", "tabasco sauce", "cholula", "valentina", "tapatio", "tapatío", "frank's redhot", "frank's red hot", "franks red hot", "louisiana hot sauce", "crystal hot sauce", "buffalo sauce", "wing sauce", "cayenne pepper sauce", "hot pepper sauce", "pepper sauce", "hot sauce of choice", "your favorite hot sauce", "hot sauce, to taste", "chipotle hot sauce", "habanero sauce", "green hot sauce", "scotch bonnet sauce"], { staple: true }),
  c("sriracha", "condiment", ["chili garlic sauce", "chili garlic paste", "sambal oelek", "sambal", "sweet chili sauce", "thai sweet chili sauce", "sweet chilli sauce", "garlic chili sauce", "sriracha sauce"], { staple: true }),
  c("gochujang", "condiment", ["korean chili paste", "korean red pepper paste", "gochujang paste", "ssamjang", "doenjang", "korean soybean paste", "doubanjiang", "chili bean paste", "chili bean sauce", "toban djan", "broad bean paste", "gochujang mayo"]),
  c("hoisin", "condiment", ["hoisin sauce", "plum sauce", "char siu sauce", "sweet bean sauce", "tianmianjiang", "black bean sauce", "black bean garlic sauce", "fermented black beans", "douchi", "teriyaki sauce", "teriyaki", "ponzu", "ponzu sauce", "yuzu ponzu", "tonkatsu sauce", "okonomiyaki sauce", "bulldog sauce", "eel sauce", "unagi sauce", "stir fry sauce", "stir-fry sauce", "bulgogi sauce", "korean bbq sauce", "korean barbecue sauce", "yakitori sauce", "general tso sauce", "kung pao sauce", "kecap"], { label: "hoisin / teriyaki / stir-fry sauces" }),
  c("oyster-sauce", "condiment", ["oyster sauce", "xo sauce", "vegetarian oyster sauce", "vegan oyster sauce", "mushroom oyster sauce", "vegetarian stir fry sauce"], { animal: true }),
  c("worcestershire", "condiment", ["worcestershire sauce", "lea & perrins", "worcester sauce", "vegan worcestershire", "worcestershire sauce, vegan"], { staple: true, animal: true }),
  c("fish-sauce", "condiment", ["fish sauce", "thai fish sauce", "nam pla", "nuoc mam", "vietnamese fish sauce", "red boat fish sauce", "colatura", "shrimp paste", "belacan", "kapi", "dried shrimp", "vegan fish sauce"], { staple: true, animal: true }),
  c("dashi", "condiment", ["dashi stock", "dashi powder", "hondashi", "instant dashi", "dashi granules", "bonito flakes", "katsuobushi", "anchovy stock", "dashi broth", "kombu dashi"], { animal: true }),
  c("rice-wine", "condiment", ["mirin", "sake", "cooking sake", "shaoxing wine", "shaoxing", "shao hsing", "chinese cooking wine", "chinese rice wine", "michiu", "huangjiu", "dry sherry", "sherry", "cooking sherry", "rice cooking wine", "shaoxing rice wine"], { staple: true, label: "mirin / shaoxing / sherry" }),
  c("fortified-wine", "beverage", ["marsala", "marsala wine", "dry marsala", "vermouth", "dry vermouth", "port", "port wine", "madeira", "brandy", "cognac", "calvados", "kirsch", "armagnac"]),
  c("liqueur", "beverage", ["grand marnier", "cointreau", "triple sec", "orange liqueur", "amaretto", "kahlua", "coffee liqueur", "baileys", "irish cream", "frangelico", "chambord", "limoncello", "pernod", "ouzo", "sambuca", "absinthe", "campari", "aperol", "bitters", "angostura bitters", "creme de cacao", "creme de menthe", "creme de cassis", "cassis", "chartreuse", "benedictine", "drambuie", "galliano", "midori", "blue curacao", "curacao", "curaçao", "maraschino liqueur", "luxardo", "st germain", "st-germain", "elderflower liqueur", "elderflower cordial", "liqueur of choice", "schnapps", "peach schnapps", "sloe gin", "jagermeister", "fireball", "southern comfort"]),
  c("curry-powder", "spice", ["curry powder", "madras curry powder", "mild curry powder", "hot curry powder", "yellow curry powder", "garam masala", "tandoori masala", "chaat masala", "biryani masala", "sambar powder", "berbere", "ras el hanout", "baharat", "vadouvan"], { staple: true }),
  c("curry-paste", "condiment", ["curry paste", "red curry paste", "green curry paste", "yellow curry paste", "thai red curry paste", "thai green curry paste", "massaman curry paste", "panang curry paste", "tikka masala paste", "madras curry paste", "japanese curry roux", "curry roux", "golden curry", "curry cubes", "curry blocks", "thai curry paste", "laksa paste", "rendang paste", "korma paste", "balti paste", "vindaloo paste", "rogan josh paste"]),
  c("pesto", "condiment", ["basil pesto", "prepared pesto", "store-bought pesto", "jarred pesto", "pesto sauce", "sun dried tomato pesto", "sun-dried tomato pesto", "red pesto", "green pesto", "vegan pesto", "pesto genovese", "homemade pesto"]),
  c("salsa", "condiment", ["chunky salsa", "jarred salsa", "salsa of choice", "red salsa", "salsa roja", "pico de gallo", "fresh salsa", "mild salsa", "medium salsa", "hot salsa", "restaurant style salsa", "restaurant-style salsa", "store-bought salsa", "your favorite salsa"]),
  c("enchilada-sauce", "condiment", ["enchilada sauce", "red enchilada sauce", "green enchilada sauce", "taco sauce", "mole", "mole sauce", "mole paste", "adobo sauce", "chipotle sauce", "ranchero sauce", "canned enchilada sauce", "homemade enchilada sauce"]),
  c("hummus", "condiment", ["baba ganoush", "baba ghanoush", "muhammara", "tzatziki", "tzatziki sauce", "toum", "raita", "yogurt sauce", "store-bought hummus", "plain hummus", "garlic hummus", "roasted red pepper hummus"]),
  c("salad-dressing", "condiment", ["salad dressing", "ranch", "ranch dressing", "ranch dressing mix", "ranch seasoning", "blue cheese dressing", "bleu cheese dressing", "caesar dressing", "italian dressing", "italian salad dressing", "zesty italian dressing", "vinaigrette", "balsamic vinaigrette", "greek dressing", "dressing of choice", "honey mustard dressing", "thousand island", "thousand island dressing", "russian dressing", "french dressing", "catalina dressing", "sesame ginger dressing", "sesame dressing", "ginger dressing", "asian dressing", "peanut dressing", "goddess dressing", "green goddess dressing", "poppy seed dressing", "coleslaw dressing", "slaw dressing", "tahini dressing", "lemon tahini dressing", "tahini sauce", "remoulade", "tartar sauce", "tartare sauce", "your favorite dressing", "store-bought dressing", "bottled dressing"]),
  c("alfredo-sauce", "condiment", ["alfredo sauce", "alfredo", "jarred alfredo sauce", "bechamel", "béchamel", "cheese sauce", "white sauce", "queso dip", "queso sauce", "nacho cheese", "nacho cheese sauce", "cheese dip"]),
  c("gravy", "condiment", ["brown gravy", "gravy mix", "au jus", "au jus mix", "onion soup mix", "french onion soup mix", "dry onion soup mix", "gravy granules", "bisto", "turkey gravy", "chicken gravy", "beef gravy", "sausage gravy", "country gravy", "white gravy"]),
  c("harissa", "condiment", ["harissa paste", "rose harissa", "romesco", "romesco sauce", "ajvar", "chermoula", "chermoula paste", "chimichurri", "chimichurri sauce", "zhoug", "zhug", "schug", "shatta", "tapenade", "olive tapenade", "salsa verde (italian)", "gremolata"], { label: "harissa / romesco / chimichurri" }),
  c("chutney", "condiment", ["mango chutney", "tamarind chutney", "mint chutney", "cilantro chutney", "coriander chutney", "green chutney", "coconut chutney", "tomato chutney", "onion chutney", "lime pickle", "indian pickle", "achar", "achaar", "mango pickle", "branston pickle", "fruit chutney", "apple chutney", "date chutney", "imli chutney"]),
  c("cranberry-sauce", "condiment", ["cranberry sauce", "canned cranberry sauce", "whole berry cranberry sauce", "jellied cranberry sauce", "cranberry relish", "mint sauce", "mint jelly", "redcurrant jelly", "red currant jelly"]),
  c("relish", "condiment", ["pickle relish", "sweet relish", "dill relish", "sweet pickle relish", "hot dog relish", "chow chow", "piccalilli", "corn relish", "onion relish", "tomato relish", "capsicum relish"]),
  c("tamarind", "condiment", ["tamarind paste", "tamarind concentrate", "tamarind pulp", "tamarind sauce", "pad thai sauce", "tamarind puree", "tamarind purée", "tamarind block", "wet tamarind", "tamarind water", "tamarind juice"]),
  c("peanut-sauce", "condiment", ["peanut sauce", "satay sauce", "thai peanut sauce", "peanut dipping sauce", "spicy peanut sauce"]),
  c("horseradish", "condiment", ["prepared horseradish", "fresh horseradish", "grated horseradish", "horseradish sauce", "creamed horseradish", "wasabi", "wasabi powder", "wasabi paste", "wasabi mayo", "yuzu kosho", "horseradish cream", "horseradish root"]),
  c("liquid-smoke", "condiment", ["liquid smoke", "smoke flavor", "smoke flavour", "hickory liquid smoke", "mesquite liquid smoke"]),
  c("msg", "spice", ["monosodium glutamate", "ajinomoto", "accent seasoning", "citric acid", "sansho", "sansho pepper", "mushroom powder", "mushroom seasoning", "umami powder", "umami seasoning", "porcini powder", "shiitake powder", "chicken powder", "chicken bouillon powder", "knorr chicken powder", "totole", "lee kum kee chicken powder"], { label: "msg / umami seasoning" }),
  c("sugar", "sweetener", ["granulated sugar", "white sugar", "caster sugar", "castor sugar", "superfine sugar", "cane sugar", "raw sugar", "turbinado sugar", "demerara sugar", "coconut sugar", "organic cane sugar", "regular sugar", "sugar, divided", "white granulated sugar", "fine sugar", "sugar of choice", "sweetener of choice", "sweetener", "monk fruit sweetener", "monkfruit", "erythritol", "stevia", "swerve", "xylitol", "allulose", "sugar substitute", "splenda", "sugar free sweetener", "keto sweetener", "low carb sweetener", "granulated sweetener", "date sugar", "palm sugar", "jaggery", "gur", "piloncillo", "panela", "rapadura", "muscovado", "muscovado sugar", "dark muscovado", "light muscovado", "golden caster sugar", "golden sugar", "sanding sugar", "sparkling sugar", "pearl sugar", "rock sugar", "yellow rock sugar", "chinese rock sugar", "candy sugar", "sugar cubes", "vanilla sugar", "sugar in the raw", "sugar, plus more", "sugar, to taste", "sugar to taste", "pinch of sugar"], { staple: true }),
  c("powdered-sugar", "sweetener", ["powdered sugar", "confectioners sugar", "confectioners' sugar", "confectioner's sugar", "icing sugar", "10x sugar", "powdered sugar, sifted", "sifted powdered sugar"], { staple: true }),
  c("corn-syrup", "sweetener", ["corn syrup", "light corn syrup", "dark corn syrup", "karo syrup", "golden syrup", "glucose syrup", "liquid glucose", "invert sugar", "simple syrup", "sugar syrup", "gomme syrup", "gum syrup", "treacle", "cane syrup", "rice syrup", "brown rice syrup", "malt syrup", "barley malt syrup", "lyle's golden syrup"]),
  c("molasses", "sweetener", ["blackstrap molasses", "unsulphured molasses", "black treacle", "sorghum", "sorghum syrup", "dark molasses", "light molasses", "fancy molasses", "grape molasses", "pekmez", "carob syrup", "date molasses", "date honey", "silan"]),
  c("agave", "sweetener", ["agave nectar", "agave syrup", "light agave", "dark agave", "raw agave", "coconut nectar", "yacon syrup", "birch syrup"]),
  c("jam", "sweetener", ["jelly", "preserves", "marmalade", "fruit preserves", "strawberry jam", "raspberry jam", "apricot jam", "apricot preserves", "orange marmalade", "fig jam", "fig preserves", "blackberry jam", "blueberry jam", "peach preserves", "peach jam", "grape jelly", "cherry jam", "cherry preserves", "plum jam", "lemon curd", "lime curd", "passion fruit curd", "fruit curd", "apple butter", "pumpkin butter", "quince paste", "membrillo", "guava paste", "strawberry preserves", "raspberry preserves", "jam of choice", "your favorite jam", "any jam", "fruit spread", "fruit jam", "berry jam", "mixed berry jam", "seedless raspberry jam", "seedless jam", "chia jam", "mango jam", "pineapple jam", "rhubarb jam", "blackcurrant jam", "black currant jam", "damson jam", "gooseberry jam", "lingonberry jam", "rose petal jam", "yuzu marmalade", "lemon marmalade", "lime marmalade", "grapefruit marmalade", "ginger jam", "ginger marmalade", "hot pepper jelly", "pepper jelly", "jalapeno jelly", "jalapeño jelly", "red pepper jelly", "bacon jam", "onion jam", "tomato jam", "fig spread", "fruit butter"]),
  c("caramel", "sweetener", ["caramel sauce", "caramel syrup", "salted caramel", "salted caramel sauce", "dulce de leche sauce", "butterscotch sauce", "toffee sauce", "caramels", "soft caramels", "caramel candies", "kraft caramels", "caramel bits", "toffee bits", "toffee", "heath bits", "english toffee", "butterscotch chips", "caramel topping", "caramel ice cream topping", "cajeta"]),
  c("chocolate-syrup", "sweetener", ["chocolate syrup", "chocolate sauce", "hot fudge", "hot fudge sauce", "fudge sauce", "hershey's syrup", "chocolate ganache", "ganache", "chocolate topping", "magic shell"]),
  c("marshmallow", "sweetener", ["marshmallows", "mini marshmallows", "large marshmallows", "marshmallow fluff", "marshmallow creme", "marshmallow cream", "vegan marshmallows", "jumbo marshmallows"]),
  c("candy", "sweetener", ["sprinkles", "rainbow sprinkles", "chocolate sprinkles", "nonpareils", "jimmies", "edible glitter", "peanut butter chips", "cinnamon chips", "candy melts", "candy coating", "almond bark", "white almond bark", "candy corn", "m&ms", "m&m's", "m & m's", "reese's pieces", "reese's cups", "peanut butter cups", "candy bars", "chopped candy bars", "snickers", "kit kat", "kit kats", "twix", "rolos", "rolo", "skittles", "gummy bears", "gummies", "gummy worms", "candy canes", "candy cane", "peppermint candies", "peppermints", "starlight mints", "andes mints", "maraschino cherries", "candied fruit", "candied peel", "candied orange peel", "candied lemon peel", "mixed peel", "glace cherries", "glacé cherries", "candied ginger", "crystallized ginger", "crystallised ginger", "stem ginger", "stem ginger in syrup", "candied citrus", "marzipan", "almond paste", "fondant", "praline paste", "pistachio paste", "gianduja", "halva", "halvah", "turkish delight", "lokum", "nougat", "brittle", "peanut brittle", "pralines", "fudge", "chocolate truffles", "truffles (candy)", "chocolate covered espresso beans", "chocolate covered raisins", "chocolate covered pretzels", "malted milk balls", "whoppers", "maltesers", "toblerone", "ferrero rocher", "lindt truffles", "hershey's kisses", "hershey kisses", "kisses", "hershey bars", "hershey bar", "cadbury", "cadbury eggs", "creme eggs", "mini eggs", "jelly beans", "jellybeans", "licorice", "liquorice", "twizzlers", "red vines", "sour patch kids", "swedish fish", "nerds", "pop rocks", "sixlets", "smarties", "rockets", "candy buttons", "lollipops", "lollipop", "suckers", "dum dums", "tootsie rolls", "tootsie pops", "jolly ranchers", "werther's", "butterscotch candies", "butterscotch discs", "cinnamon candies", "red hots", "hot tamales", "mike and ikes", "junior mints", "york peppermint patties", "peppermint patties", "thin mints"]),
  c("food-coloring", "baking", ["food coloring", "food colouring", "gel food coloring", "gel food colouring", "red food coloring", "green food coloring", "blue food coloring", "yellow food coloring", "food dye", "natural food coloring", "food color", "liquid food coloring", "americolor", "wilton gel", "beet powder (for color)", "matcha (for color)", "spirulina powder", "butterfly pea powder", "activated charcoal", "charcoal powder", "black cocoa (for color)", "freeze-dried strawberry powder", "freeze dried strawberry powder", "freeze-dried raspberry powder", "freeze dried raspberry powder", "freeze-dried fruit powder", "fruit powder"]),
  c("cookies", "sweetener", ["oreos", "oreo cookies", "oreo", "chocolate sandwich cookies", "vanilla wafers", "nilla wafers", "shortbread cookies", "shortbread", "biscoff", "biscoff cookies", "speculoos", "cookie butter", "biscoff spread", "digestive biscuits", "digestives", "ladyfingers", "lady fingers", "savoiardi", "graham crackers", "graham cracker crumbs", "graham cracker", "gingersnaps", "ginger snaps", "gingersnap cookies", "ginger biscuits", "ginger nuts", "amaretti", "amaretti cookies", "biscotti", "wafer cookies", "wafers", "sugar cookies", "chocolate chip cookies", "cookie crumbs", "cookie dough", "refrigerated cookie dough", "sugar cookie dough", "chocolate chip cookie dough", "brownies", "brownie", "leftover cake", "cake crumbs", "cake scraps", "pretzels", "pretzel", "mini pretzels", "pretzel sticks", "pretzel rods", "crushed pretzels", "pretzel crumbs", "rice krispies", "rice crispies", "crispy rice cereal", "puffed rice", "puffed rice cereal", "cereal", "corn flakes", "cornflakes", "frosted flakes", "cheerios", "granola", "granola of choice", "store-bought granola", "chex", "chex cereal", "rice chex", "corn chex", "wheat chex", "cinnamon toast crunch", "fruity pebbles", "cocoa pebbles", "lucky charms", "froot loops", "fruit loops", "cap'n crunch", "captain crunch", "golden grahams", "honey bunches of oats", "special k", "all-bran", "bran flakes", "bran cereal", "shredded wheat", "wheaties", "grape nuts", "grape-nuts", "muesli", "bircher muesli", "weetabix", "weet-bix", "cereal of choice", "your favorite cereal", "any cereal", "kids cereal", "puffed wheat", "puffed quinoa", "puffed millet", "puffed amaranth", "popcorn", "popped popcorn", "popcorn kernels", "microwave popcorn", "kettle corn", "caramel corn", "cracker jack", "cracker jacks"], { label: "cookies, crackers & cereal" }),
  c("cake-mix", "baking", ["cake mix", "yellow cake mix", "white cake mix", "chocolate cake mix", "devil's food cake mix", "spice cake mix", "lemon cake mix", "strawberry cake mix", "red velvet cake mix", "funfetti cake mix", "boxed cake mix", "box cake mix", "brownie mix", "boxed brownie mix", "muffin mix", "pancake mix", "waffle mix", "bisquick", "baking mix", "cornbread mix", "jiffy cornbread mix", "jiffy mix", "biscuit mix", "cookie mix", "sugar cookie mix", "chocolate chip cookie mix", "bread mix", "pizza dough mix", "scone mix", "angel food cake mix", "pound cake mix", "sponge cake", "pound cake", "angel food cake", "store-bought pound cake", "store bought angel food cake", "premade cake", "store-bought cake", "shortcake", "shortcakes", "sponge fingers", "genoise", "cake layers", "premade crust", "graham cracker crust", "premade graham cracker crust", "store-bought graham cracker crust", "oreo crust", "chocolate cookie crust", "cookie crust", "tart shell", "tart shells", "pastry shell", "pastry shells", "pie shell", "pie shells", "frozen pie shell", "frozen pie crust", "puff pastry shells", "vol-au-vent", "phyllo cups", "phyllo shells", "mini phyllo cups", "tartlet shells", "cannoli shells", "waffle cones", "ice cream cones", "sugar cones", "waffle bowls", "ice cream sandwiches", "ice cream bars", "popsicles", "ice pops", "sorbet", "sherbet", "frozen yogurt", "froyo", "frozen custard", "soft serve", "kulfi", "mochi", "mochi ice cream", "daifuku", "dango", "rice cakes", "korean rice cakes", "tteok", "tteokbokki rice cakes", "garaetteok", "nian gao", "rice cake (korean)", "rice cakes (korean)", "mochi rice cakes", "kirimochi", "rice crackers", "senbei", "arare", "puffed rice cakes", "quaker rice cakes", "rice cake (puffed)", "corn cakes", "corn thins", "rice thins", "crispbread", "crisp bread", "ryvita", "wasa", "knäckebröd", "matzo", "matzah", "matzo meal", "matzo crackers", "matzo ball mix", "water crackers", "table water crackers", "carr's crackers", "triscuits", "wheat thins", "cheez-its", "cheez its", "cheese crackers", "goldfish", "goldfish crackers", "animal crackers", "teddy grahams", "club crackers", "town house crackers", "butter crackers", "oyster crackers", "pilot crackers", "hardtack", "pita chips", "bagel chips", "melba toast", "breadsticks", "grissini", "taralli", "lavash crackers", "lavash", "papadum", "papadums", "poppadoms", "pappadam", "prawn crackers", "shrimp chips", "krupuk", "kerupuk", "emping", "cassava chips", "plantain chips", "banana chips", "apple chips", "veggie chips", "kale chips", "beet chips", "sweet potato chips", "potato chips", "crisps", "kettle chips", "salt and vinegar chips", "bbq chips", "sour cream and onion chips", "doritos", "cheetos", "fritos", "corn chips", "takis", "funyuns", "pork rinds", "chicharrones", "chicharron", "pork scratchings", "pork crackling", "crackling", "cracklings", "gribenes"], { label: "cake mix, crusts & snacks" }),
  c("pudding-mix", "baking", ["pudding mix", "instant pudding", "instant pudding mix", "vanilla pudding mix", "chocolate pudding mix", "vanilla instant pudding", "chocolate instant pudding", "butterscotch pudding mix", "pistachio pudding mix", "lemon pudding mix", "cheesecake pudding mix", "banana pudding mix", "jello", "jell-o", "gelatin dessert", "jello mix", "jell-o mix", "flavored gelatin", "strawberry jello", "lime jello", "orange jello", "custard powder", "bird's custard powder", "instant custard", "custard mix", "flan mix", "mousse mix", "cheesecake mix", "no-bake cheesecake mix", "whipped topping mix", "dream whip", "pastry cream", "creme patissiere", "crème pâtissière", "vanilla custard", "custard", "premade custard", "store-bought custard", "ambrosia custard", "pudding", "vanilla pudding", "chocolate pudding", "rice pudding", "tapioca pudding", "bread pudding", "banana pudding", "snack pack pudding", "pudding cups"]),
  c("whipped-topping", "dairy", ["whipped topping", "cool whip", "whipped cream", "canned whipped cream", "reddi-wip", "reddi whip", "sweetened whipped cream", "fresh whipped cream", "homemade whipped cream", "stabilized whipped cream", "coconut whipped cream", "vegan whipped cream", "non-dairy whipped topping", "truwhip", "so delicious cocowhip", "cocowhip", "whipped coconut cream", "chantilly cream", "creme chantilly", "crème chantilly", "squirty cream", "spray cream", "aerosol cream", "aerosol whipped cream", "whipped cream for serving", "whipped cream, for serving", "whipped cream, optional", "whipped cream (optional)"]),
  c("frosting", "sweetener", ["icing", "canned frosting", "store-bought frosting", "buttercream", "buttercream frosting", "cream cheese frosting", "chocolate frosting", "vanilla frosting", "royal icing", "cream cheese icing", "chocolate icing", "vanilla icing", "glaze (icing)", "powdered sugar glaze", "vanilla glaze", "lemon glaze", "cinnamon roll icing", "cookie icing", "decorating icing", "piping icing", "writing icing", "gel icing", "fondant icing", "ganache frosting", "whipped frosting", "ermine frosting", "seven minute frosting", "7-minute frosting", "boiled icing", "marshmallow frosting", "fluffy frosting", "cooked frosting", "german chocolate frosting", "coconut pecan frosting", "peanut butter frosting", "caramel frosting", "maple frosting", "coffee frosting", "mocha frosting", "strawberry frosting", "raspberry frosting", "lemon frosting", "orange frosting", "funfetti frosting", "sprinkle frosting", "rainbow chip frosting", "sour cream frosting", "mascarpone frosting", "whipped cream frosting", "stabilized whipped cream frosting", "cool whip frosting", "dream whip frosting", "pudding frosting", "jello frosting", "fruit frosting", "berry frosting", "frosting of choice", "your favorite frosting", "any frosting"]),
  c("plant-milk", "beverage", ["almond milk", "unsweetened almond milk", "oat milk", "soy milk", "soya milk", "cashew milk", "rice milk", "hemp milk", "plant milk", "plant-based milk", "plant based milk", "non-dairy milk", "nondairy milk", "non dairy milk", "dairy-free milk", "dairy free milk", "milk alternative", "vegan milk", "almond or oat milk", "oat or almond milk", "unsweetened plant milk", "unsweetened non-dairy milk", "unsweetened oat milk", "unsweetened soy milk", "unsweetened cashew milk", "vanilla almond milk", "barista oat milk", "macadamia milk", "pea milk", "flax milk", "nut milk", "milk of choice (dairy-free)", "dairy-free milk of choice", "non-dairy milk of choice", "plant milk of choice", "any plant milk", "any non-dairy milk", "your favorite plant milk", "unsweetened plant-based milk", "unsweetened almond or oat milk", "unsweetened nondairy milk", "soymilk", "almondmilk", "oatmilk", "coconut milk beverage", "coconut milk (carton)", "refrigerated coconut milk", "carton coconut milk", "coconut beverage", "so delicious coconut milk", "silk almond milk", "silk soy milk", "califia almond milk", "oatly", "oatly oat milk", "chobani oat milk", "planet oat", "ripple milk", "ripple pea milk", "elmhurst milk", "malk", "three trees almond milk", "new barn almond milk", "forager cashew milk", "milkadamia", "good karma flax milk"]),
  c("nuts", "nut", ["almonds", "sliced almonds", "slivered almonds", "toasted almonds", "whole almonds", "raw almonds", "roasted almonds", "marcona almonds", "almond", "walnuts", "walnut", "chopped walnuts", "toasted walnuts", "walnut halves", "pecans", "pecan", "chopped pecans", "pecan halves", "toasted pecans", "cashews", "cashew", "raw cashews", "roasted cashews", "cashew nuts", "pistachios", "pistachio", "shelled pistachios", "pistachio nuts", "hazelnuts", "hazelnut", "filberts", "macadamia nuts", "macadamias", "macadamia", "pine nuts", "pine nut", "pignoli", "toasted pine nuts", "brazil nuts", "chestnuts", "roasted chestnuts", "mixed nuts", "nuts of choice", "chopped nuts", "candied nuts", "candied pecans", "candied walnuts", "nut of choice", "almond slivers", "almond slices", "flaked almonds", "ground hazelnuts", "hazelnut meal", "pecan meal", "walnut meal", "nut meal", "almond butter", "cashew butter", "sunflower seed butter", "sunbutter", "nut butter", "nut butter of choice", "coconut butter", "pine kernels", "tigernuts", "tiger nuts", "sacha inchi"]),
  c("seeds", "nut", ["pumpkin seeds", "pepitas", "sunflower seeds", "chia seeds", "chia", "flax seeds", "flaxseed", "flaxseeds", "ground flaxseed", "ground flax", "flax meal", "flaxseed meal", "hemp seeds", "hemp hearts", "hulled hemp seeds", "mixed seeds", "seeds of choice", "toasted seeds", "roasted pumpkin seeds", "roasted sunflower seeds", "raw pumpkin seeds", "raw sunflower seeds", "poppy seeds", "poppy seed", "watermelon seeds", "lotus seeds", "melon seeds", "psyllium husk", "psyllium", "psyllium husk powder", "basil seeds", "sabja seeds", "tukmaria"]),
  c("water", "beverage", ["cold water", "warm water", "hot water", "boiling water", "ice water", "ice", "ice cubes", "crushed ice", "filtered water", "tap water", "lukewarm water", "room temperature water", "cool water", "water, divided", "water as needed", "water, as needed", "water for boiling", "salted water", "water, for boiling", "water, plus more", "extra water", "additional water", "more water", "enough water", "water to cover", "water, to cover", "pasta water", "reserved pasta water", "reserved cooking water", "starchy pasta water", "pasta cooking water", "cooking liquid", "reserved liquid", "cooking water", "still water", "mineral water", "sparkling water", "seltzer", "seltzer water", "club soda", "soda water", "perrier", "san pellegrino", "pellegrino"], { staple: true }),
  c("aquafaba", "legume", ["chickpea water", "chickpea liquid", "liquid from can of chickpeas", "reserved chickpea liquid", "bean cooking liquid", "chickpea brine", "liquid from canned chickpeas", "aquafaba (chickpea liquid)", "chickpea aquafaba"]),
  c("juice", "beverage", ["apple juice", "cranberry juice", "tomato juice", "vegetable juice", "v8", "v8 juice", "clamato", "grape juice", "white grape juice", "cherry juice", "tart cherry juice", "mango juice", "mango nectar", "peach nectar", "apricot nectar", "guava juice", "guava nectar", "passion fruit juice", "passionfruit juice", "lychee juice", "coconut water", "aloe vera juice", "aloe juice", "carrot juice", "beet juice", "celery juice", "cucumber juice", "watermelon juice", "fruit juice", "juice of choice", "any juice", "100% juice", "unsweetened juice", "fruit nectar", "nectar", "lemonade", "limeade", "pink lemonade", "fruit punch", "punch", "hawaiian punch", "kool-aid", "kool aid", "tang", "apple cider", "fresh apple cider", "sweet cider", "unfiltered apple juice", "cloudy apple juice", "pear juice", "pear nectar"]),
  c("soda", "beverage", ["cola", "coke", "coca-cola", "coca cola", "pepsi", "diet coke", "diet soda", "root beer", "ginger ale", "ginger beer", "tonic", "tonic water", "lemon-lime soda", "lemon lime soda", "sprite", "7up", "7-up", "mountain dew", "dr pepper", "dr. pepper", "cream soda", "orange soda", "fanta", "grape soda", "cherry cola", "italian soda", "sports drink", "gatorade", "energy drink", "red bull", "kombucha", "soda of choice", "any soda", "soft drink", "fizzy drink", "pop", "soda pop"]),
  c("tea", "beverage", ["black tea", "green tea", "matcha", "matcha powder", "earl grey", "earl grey tea", "chai", "chai tea", "chai concentrate", "masala chai", "chai spice", "chai spice mix", "chai masala", "tea bags", "tea bag", "loose leaf tea", "herbal tea", "chamomile tea", "chamomile", "hibiscus", "dried hibiscus", "hibiscus flowers", "jasmine tea", "oolong", "oolong tea", "rooibos", "white tea", "mint tea", "peppermint tea", "yerba mate", "hojicha", "genmaicha", "sencha", "english breakfast tea", "english breakfast", "irish breakfast", "thai tea", "thai tea mix", "boba", "tapioca pearls", "boba pearls", "tapioca balls", "brewed tea", "strong tea", "chilled tea", "iced tea", "sweet tea", "tea of choice", "any tea", "tea leaves", "tea concentrate", "butterfly pea flower", "butterfly pea tea", "barley tea", "corn tea", "buckwheat tea", "ginger tea", "lemon tea", "honey lemon tea", "turmeric tea", "golden milk", "ceylon tea", "assam", "darjeeling", "lapsang souchong", "pu-erh", "pu erh", "gyokuro", "kukicha", "bancha", "tea, brewed"]),
];

// --- Derived lookups ------------------------------------------------------

export const CANONICAL_BY_ID = Object.fromEntries(CANONICALS.map((x) => [x.id, x]));

export const DEFAULT_SPICERACK = CANONICALS.filter((x) => x.staple).map((x) => x.id);

const ANIMAL_CATEGORIES = new Set(["meat", "poultry", "fish", "shellfish", "egg", "dairy"]);
const MEAT_CATEGORIES = new Set(["meat", "poultry"]);
const SEA_CATEGORIES = new Set(["fish", "shellfish"]);

export function isAnimal(id) {
  const x = CANONICAL_BY_ID[id];
  return !!x && (ANIMAL_CATEGORIES.has(x.category) || x.animal);
}
export function isMeat(id) {
  const x = CANONICAL_BY_ID[id];
  return !!x && MEAT_CATEGORIES.has(x.category);
}
export function isSeafood(id) {
  const x = CANONICAL_BY_ID[id];
  return !!x && (SEA_CATEGORIES.has(x.category) || id === "fish-sauce");
}
export function isDairy(id) {
  const x = CANONICAL_BY_ID[id];
  return !!x && x.category === "dairy";
}
export function hasGluten(id) {
  const x = CANONICAL_BY_ID[id];
  return !!x && x.gluten;
}
// Ingredients that carry a meal: used for the "hero" diversity rule so three
// dealt recipes do not all fight over the same pack of chicken.
export function isHero(id) {
  const x = CANONICAL_BY_ID[id];
  return !!x && (ANIMAL_CATEGORIES.has(x.category) && x.category !== "dairy" && x.category !== "egg" || x.category === "legume");
}

/** For autocomplete: [{id, label, category}] sorted by label. */
export const INGREDIENT_OPTIONS = CANONICALS
  .map(({ id, label, category }) => ({ id, label, category }))
  .sort((a, b) => a.label.localeCompare(b.label));
